export enum ReminderType {
  TIME = "TIME",
  LOCATION = "LOCATION",
  HABIT = "HABIT",
  HYBRID = "HYBRID"
}

export enum ReminderStatus {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  DELETED = "DELETED",
  SNOOZED = "SNOOZED"
}

export enum LocationTriggerType {
  ARRIVAL = "ARRIVAL",
  DEPARTURE = "DEPARTURE"
}

export enum HabitFrequencyType {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  CUSTOM = "CUSTOM"
}

export enum ReminderEventType {
  CREATED = "CREATED",
  TRIGGERED = "TRIGGERED",
  COMPLETED = "COMPLETED",
  SNOOZED = "SNOOZED",
  DISMISSED = "DISMISSED",
  EDITED = "EDITED",
  DELETED = "DELETED"
}

export enum DevicePlatform {
  IOS = "IOS",
  ANDROID = "ANDROID",
  WEB = "WEB"
}

export enum DeliveryMode {
  PUSH = "PUSH",
  VOICE = "VOICE",
  VOICE_AND_PUSH = "VOICE_AND_PUSH",
  SILENT = "SILENT",
  URGENT = "URGENT"
}

export enum ActionType {
  DRAFT_EMAIL = "DRAFT_EMAIL",
  DRAFT_MESSAGE = "DRAFT_MESSAGE",
  OPEN_PAYMENT_APP = "OPEN_PAYMENT_APP",
  PAYMENT_REMINDER = "PAYMENT_REMINDER",
  CALL_CONTACT = "CALL_CONTACT",
  OPEN_MAPS = "OPEN_MAPS",
  OPEN_URL = "OPEN_URL",
  CREATE_CALENDAR_EVENT = "CREATE_CALENDAR_EVENT",
  GENERATE_CHECKLIST = "GENERATE_CHECKLIST",
  PREPARE_MEETING_NOTES = "PREPARE_MEETING_NOTES"
}

export enum ActionPromptStatus {
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED"
}

export enum ActionPromptEventType {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  CONTENT_GENERATED = "CONTENT_GENERATED"
}

export enum TriggerType {
  TIME = "TIME",
  LOCATION_ARRIVAL = "LOCATION_ARRIVAL",
  LOCATION_DEPARTURE = "LOCATION_DEPARTURE",
  HABIT = "HABIT",
  WEATHER = "WEATHER",
  EXCHANGE_RATE = "EXCHANGE_RATE",
  PRICE = "PRICE",
  CONTACT = "CONTACT",
  TRAVEL = "TRAVEL"
}

export enum TriggerStatus {
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
  COMPLETED = "COMPLETED",
  DELETED = "DELETED"
}

export enum MemoryType {
  PERSON = "PERSON",
  PLACE = "PLACE",
  PRICE = "PRICE",
  DEBT = "DEBT",
  FAVOUR = "FAVOUR",
  PROMISE = "PROMISE",
  PREFERENCE = "PREFERENCE",
  TRAVEL = "TRAVEL",
  ROUTINE = "ROUTINE",
  DOCUMENT = "DOCUMENT",
  GENERAL = "GENERAL"
}

export enum MemorySource {
  MANUAL = "MANUAL",
  AI_EXTRACTED = "AI_EXTRACTED",
  IMPORTED = "IMPORTED",
  SHARE_EXTENSION = "SHARE_EXTENSION",
  SYSTEM_SUGGESTED = "SYSTEM_SUGGESTED"
}

export enum MemoryStatus {
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED"
}

export enum MemoryEventType {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED",
  USED_IN_TRIGGER = "USED_IN_TRIGGER"
}

export enum LiveContextTriggerType {
  WEATHER = "WEATHER",
  EXCHANGE_RATE = "EXCHANGE_RATE",
  PRICE = "PRICE",
  TRAVEL = "TRAVEL"
}

export enum LiveContextTriggerStatus {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  TRIGGERED = "TRIGGERED",
  DELETED = "DELETED"
}

export enum PriceLogSource {
  MANUAL = "MANUAL",
  OCR = "OCR",
  AI_PARSE = "AI_PARSE",
  AI_CHAT = "AI_CHAT",
  SHARE_EXTENSION = "SHARE_EXTENSION"
}

export enum BriefingType {
  MORNING = "MORNING",
  EVENING = "EVENING",
  TRAVEL = "TRAVEL",
  CUSTOM = "CUSTOM"
}

export enum PromiseStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  OVERDUE = "OVERDUE",
  CANCELLED = "CANCELLED"
}

export enum DebtDirection {
  OWED_TO_ME = "OWED_TO_ME",
  I_OWE = "I_OWE"
}

export enum DebtStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  CANCELLED = "CANCELLED"
}

export enum TravelPlanStatus {
  PLANNED = "PLANNED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum AccountabilityStrictness {
  GENTLE = "GENTLE",
  BALANCED = "BALANCED",
  STRICT = "STRICT"
}

export enum AccountabilityGoalStatus {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum AccountabilityCheckInStatus {
  DONE = "DONE",
  MISSED = "MISSED",
  SNOOZED = "SNOOZED"
}

export enum FollowUpSourceType {
  REMINDER = "REMINDER",
  ACTION = "ACTION",
  MEMORY = "MEMORY",
  TRAVEL = "TRAVEL",
  PRICE = "PRICE",
  PROMISE = "PROMISE",
  DEBT = "DEBT"
}

export enum FollowUpSuggestionStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DISMISSED = "DISMISSED",
  EXPIRED = "EXPIRED"
}

export enum ShareCaptureContentType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  URL = "URL",
  FILE = "FILE"
}

export enum ShareCaptureStatus {
  RECEIVED = "RECEIVED",
  PARSED = "PARSED",
  CONFIRMED = "CONFIRMED",
  DISCARDED = "DISCARDED"
}

export enum VoicePersonalityStyle {
  CALM = "CALM",
  PROFESSIONAL = "PROFESSIONAL",
  FRIENDLY_NIGERIAN = "FRIENDLY_NIGERIAN",
  STRICT_COACH = "STRICT_COACH",
  MINIMAL = "MINIMAL",
  ENERGETIC = "ENERGETIC"
}

export enum ChatMessageRole {
  USER = "USER",
  ASSISTANT = "ASSISTANT",
  SYSTEM = "SYSTEM",
  TOOL = "TOOL"
}

export enum AgentRunStatus {
  PLANNING = "PLANNING",
  WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION",
  EXECUTING = "EXECUTING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum ToolExecutionStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED"
}

export enum UserApprovalDecision {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EDITED = "EDITED"
}
