export enum ReminderType {
  TIME = "TIME",
  LOCATION = "LOCATION",
  HABIT = "HABIT",
  HYBRID = "HYBRID"
}

export enum ReminderStatus {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  DELETED = "DELETED",
  SNOOZED = "SNOOZED"
}

export enum LocationTriggerType {
  ARRIVAL = "ARRIVAL",
  DEPARTURE = "DEPARTURE"
}

export enum HabitFrequencyType {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  CUSTOM = "CUSTOM"
}

export enum ReminderEventType {
  CREATED = "CREATED",
  TRIGGERED = "TRIGGERED",
  COMPLETED = "COMPLETED",
  SNOOZED = "SNOOZED",
  DISMISSED = "DISMISSED",
  EDITED = "EDITED",
  DELETED = "DELETED"
}

export enum DevicePlatform {
  IOS = "IOS",
  ANDROID = "ANDROID",
  WEB = "WEB"
}

export enum DeliveryMode {
  PUSH = "PUSH",
  VOICE = "VOICE",
  VOICE_AND_PUSH = "VOICE_AND_PUSH",
  SILENT = "SILENT",
  URGENT = "URGENT"
}

export enum ActionType {
  DRAFT_EMAIL = "DRAFT_EMAIL",
  DRAFT_MESSAGE = "DRAFT_MESSAGE",
  OPEN_PAYMENT_APP = "OPEN_PAYMENT_APP",
  PAYMENT_REMINDER = "PAYMENT_REMINDER",
  CALL_CONTACT = "CALL_CONTACT",
  OPEN_MAPS = "OPEN_MAPS",
  OPEN_URL = "OPEN_URL",
  CREATE_CALENDAR_EVENT = "CREATE_CALENDAR_EVENT",
  GENERATE_CHECKLIST = "GENERATE_CHECKLIST",
  PREPARE_MEETING_NOTES = "PREPARE_MEETING_NOTES"
}

export enum ActionPromptStatus {
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED"
}

export enum ActionPromptEventType {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  CONTENT_GENERATED = "CONTENT_GENERATED"
}

export enum TriggerType {
  TIME = "TIME",
  LOCATION_ARRIVAL = "LOCATION_ARRIVAL",
  LOCATION_DEPARTURE = "LOCATION_DEPARTURE",
  HABIT = "HABIT",
  WEATHER = "WEATHER",
  EXCHANGE_RATE = "EXCHANGE_RATE",
  PRICE = "PRICE",
  CONTACT = "CONTACT",
  TRAVEL = "TRAVEL"
}

export enum TriggerStatus {
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
  COMPLETED = "COMPLETED",
  DELETED = "DELETED"
}

export enum MemoryType {
  PERSON = "PERSON",
  PLACE = "PLACE",
  PRICE = "PRICE",
  DEBT = "DEBT",
  PROMISE = "PROMISE",
  PREFERENCE = "PREFERENCE",
  TRAVEL = "TRAVEL",
  ROUTINE = "ROUTINE",
  DOCUMENT = "DOCUMENT",
  GENERAL = "GENERAL"
}

export enum MemorySource {
  MANUAL = "MANUAL",
  AI_EXTRACTED = "AI_EXTRACTED",
  IMPORTED = "IMPORTED"
}

export enum MemoryStatus {
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED"
}

export enum MemoryEventType {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED",
  USED_IN_TRIGGER = "USED_IN_TRIGGER"
}

export enum LiveContextTriggerType {
  WEATHER = "WEATHER",
  EXCHANGE_RATE = "EXCHANGE_RATE",
  PRICE = "PRICE",
  TRAVEL = "TRAVEL"
}

export enum LiveContextTriggerStatus {
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  TRIGGERED = "TRIGGERED",
  DELETED = "DELETED"
}

export enum PriceLogSource {
  MANUAL = "MANUAL",
  OCR = "OCR",
  AI_PARSE = "AI_PARSE"
}

export enum ChatMessageRole {
  USER = "USER",
  ASSISTANT = "ASSISTANT",
  SYSTEM = "SYSTEM",
  TOOL = "TOOL"
}

export enum AgentRunStatus {
  PLANNING = "PLANNING",
  WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION",
  EXECUTING = "EXECUTING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum ToolExecutionStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED"
}

export enum UserApprovalDecision {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EDITED = "EDITED"
}
